name: 'freckl'
version: 0.0.1
description: An interactive web visualiser of .freckl files.
author: Mariana Marasoiu <mariana.marasoiu@gmail.com>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  svg_pan_zoom:
    git:
      url: git://github.com/marianamarasoiu/svg_pan_zoom.git